name=Pervasive_Wide_Small
version=10.0.0
author=Pervasive Displays Inc.
maintainer=Arvin Tan <https://www.pervasivedisplays.com>
sentence=Driver for Pervasive Displays screens 
paragraph=with wide temperature and embedded fast update, small size
category=Display
url=https://github.com/PervasiveDisplays
architectures=*
depends=PDLS_Common (>=10.0.8)
